create_measure_table_query = """
-- auto-generated definition
create table measure
(
    time              timestamp not null
        constraint measure_pkey
            primary key,
    sp_plantdensity                                  double precision,
    sp_day_of_harvest_day_number                     double precision,
    sp_heating_temp_setpoint_5min                    double precision,
    sp_vent_ilation_temp_setpoint_5min               double precision,
    sp_leeside_minvent_position_setpoint_5min        double precision,
    sp_net_pipe_minimum_setpoint_5min                double precision,
    sp_Value_to_iSii_1_5min                          double precision,
    sp_energy_screen_setpoint_5min                   double precision,
    sp_blackout_screen_setpoint_5min                 double precision,
    sp_CO2_setpoint_ppm_5min                         double precision,
    sp_humidity_deficit_setpoint_5min                double precision,
    sp_irrigation_interval_time_setpoint_min_5min    double precision,
    temperature_greenhouse_5min                      double precision,
    temperature_greenhouse                           double precision,
    temperature_greenhouse_day                       double precision,
    temperature_greenhousenight                      double precision,
    RH_greenhouse_5min                               double precision,
    RH_greenhouse                                    double precision,
    RH_greenhouse_day                                double precision,
    RH_greenhousenight                               double precision,
    CO2_greenhouse_ppm_5min                          double precision,
    CO2_greenhouse_ppm                               double precision,
    CO2_greenhouse_ppm_day                           double precision,
    CO2_greenhouse_ppm_night                         double precision,
    humidity_deficit_greenhouse_5min                 double precision,
    humidity_deficit_greenhouse                      double precision,
    humidity_deficit_greenhouse_day                  double precision,
    humidity_deficit_greenhouse_night                double precision,
    vent_lee_5min                                    double precision,
    vent_lee                                         double precision,
    vent_lee_day                                     double precision,
    vent_leenight                                    double precision,
    vent_wind_5min                                   double precision,
    vent_wind                                        double precision,
    vent_wind_day                                    double precision,
    vent_wind_night                                  double precision,
    lower_circuit_5min                               double precision,
    lower_circuit                                    double precision,
    lower_circuit_day                                double precision,
    lower_circuitnight                               double precision,
    energy_curtain_5min                              double precision,
    energy_curtain                                   double precision,
    energy_curtain_day                               double precision,
    energy_curtainnight                              double precision,
    blackout_curtain_5min                            double precision,
    blackout_curtain                                 double precision,
    blackout_curtain_day                             double precision,
    blackout_curtainnight                            double precision,
    CO2_actuation_regulation_5min                    double precision,
    CO2_actuation_regulation                         double precision,
    CO2_actuation_regulation_day                     double precision,
    CO2_actuation_regulationnight                    double precision,
    CO2_dosagesum_24h_5min                           double precision,
    CO2_dosagesum_24h                                double precision,
    CO2_dosagesum_24h_day                            double precision,
    CO2_dosagesum_24hnight                           double precision,
    water_supply_minutes_5min                        double precision,
    water_supply_minutes                             double precision,
    drain_5min                                       double precision,
    drain                                            double precision,
    drain_EC_5min                                    double precision,
    drain_EC                                         double precision,
    drain_EC_day                                     double precision,
    drain_EC_night                                   double precision,
    drain_pH_5min                                    double precision,
    drain_pH                                         double precision,
    drain_pH_day                                     double precision,
    drain_pH_night                                   double precision,
    heating_temp_ViP_5min                            double precision,
    heating_temp_ViP                                 double precision,
    heating_temp_ViP_day                             double precision,
    heating_temp_ViP_night                           double precision,
    heating_temp_setpoint                            double precision,
    heating_temp_setpoint_day                        double precision,
    heating_temp_setpoint_night                      double precision,
    vent_ilation_temp_leeside_ViP_5min               double precision,
    vent_ilation_temp_leeside_ViP                    double precision,
    vent_ilation_temp_leeside_ViP_day                double precision,
    vent_ilation_temp_leeside_ViP_night              double precision,
    vent_ilation_tempwind_side_ViP_5min              double precision,
    vent_ilation_tempwind_side_ViP                   double precision,
    vent_ilation_tempwind_side_ViP_day               double precision,
    vent_ilation_tempwind_side_ViP_night             double precision,
    vent_ilation_temp_setpoint                       double precision,
    vent_ilation_temp_setpoint_day                   double precision,
    vent_ilation_temp_setpoint_night                 double precision,
    leeside_window_position_minimum_ViP_5min         double precision,
    leeside_window_position_minimum_ViP              double precision,
    leeside_window_position_minimum_ViP_day          double precision,
    leeside_window_position_minimum_ViP_night        double precision,
    leeside_minvent_position_setpoint                double precision,
    leeside_minvent_position_setpoint_day            double precision,
    leeside_minvent_position_setpoint_night          double precision,
    net_pipe_minimum_ViP_5min                        double precision,
    net_pipe_minimum_ViP                             double precision,
    net_pipe_minimum_ViP_day                         double precision,
    net_pipe_minimum_ViP_night                       double precision,
    net_pipe_minimum_setpoint                        double precision,
    net_pipe_minimum_setpoint_day                    double precision,
    net_pipe_minimum_setpoint_night                  double precision,
    Value_in_iSii_1_5min                             double precision,
    Value_in_iSii_1                                  double precision,
    Value_to_iSii_1                                  double precision,
    energy_screen_ViP_screen_position_5min           double precision,
    energy_screen_ViP_screen_position                double precision,
    energy_screen_ViP_screen_position_day            double precision,
    energy_screen_ViP_screen_position_night          double precision,
    energy_screen_setpoint                           double precision,
    energy_screen_setpoint_day                       double precision,
    energy_screen_setpoint_night                     double precision,
    blackout_screen_ViP_screen_position_5min         double precision,
    blackout_screen_ViP_screen_position              double precision,
    blackout_screen_ViP_screen_position_day          double precision,
    blackout_screen_ViP_screen_position_night        double precision,
    blackout_screen_setpoint                         double precision,
    blackout_screen_setpoint_day                     double precision,
    blackout_screen_setpoint_night                   double precision,
    CO2_ViP_ppm_5min                                 double precision,
    CO2_ViP_ppm                                      double precision,
    CO2_ViP_ppm_day                                  double precision,
    CO2_ViP_ppm_night                                double precision,
    CO2_setpoint_ppm                                 double precision,
    CO2_setpoint_ppm_day                             double precision,
    CO2_setpoint_ppm_night                           double precision,
    humidity_deficit_ViP_5min                        double precision,
    humidity_deficit_ViP                             double precision,
    humidity_deficit_ViP_day                         double precision,
    humidity_deficit_ViP_night                       double precision,
    humidity_deficit_setpoint                        double precision,
    humidity_deficit_setpoint_day                    double precision,
    humidity_deficit_setpoint_night                  double precision,
    water_supply_interval_time_ViP_min_5min          double precision,
    water_supply_interval_time_ViP_min               double precision,
    irrigation_interval_time_setpoint_min            double precision,
    Writeto_iSii_5min                                double precision,
    Writeto_iSii                                     double precision,
    outside_temperature_5min                         double precision,
    outside_temperature                              double precision,
    outside_temperature_day                          double precision,
    outside_temperature_night                        double precision,
    outside_temperature_long_standing_average        double precision,
    outside_rh_5min                                  double precision,
    outside_rh                                       double precision,
    outside_rh_day                                   double precision,
    outside_rh_night                                 double precision,
    outside_humidity_deficit_5min                    double precision,
    outside_humidity_deficit                         double precision,
    outside_humidity_deficit_day                     double precision,
    outside_humidity_deficit_night                   double precision,
    outside_absolute_humidity_content_air_5min       double precision,
    outside_absolute_humidity_content_air            double precision,
    outside_absolute_humidity_content_air_day        double precision,
    outside_absolute_humidity_content_airnight       double precision,
    outside_radiation_5min                           double precision,        
    outside_radiation                                double precision,             
    outside_radiation_sum_5min                       double precision,    
    outside_radiation_sum                            double precision,         
    outside_radiation_sum_longstanding_average       double precision,   
    outside_wind_speed_5min                          double precision,       
    outside_wind_speed                               double precision,            
    outside_wind_speed_day                           double precision,        
    outside_wind_speednight                          double precision,       
    outside_wind_direction_type                      double precision,  
    outside_wind_direction_registration_5min         double precision,      
    outside_wind_direction_registration              double precision,           
    outside_wind_direction_registration_day          double precision,       
    outside_wind_direction_registrationnight         double precision,      
    outside_wind_direction_5min                      double precision,                  
    outside_wind_direction                           double precision,                       
    outside_wind_direction_day                       double precision,                   
    outside_wind_direction_night                     double precision,                                 
    outside_rain_5min                                double precision,                             
    outside_rain                                     double precision,                                  
    outside_rain_day                                 double precision,                              
    outside_rain_night                               double precision,                            
    outside_par_measurement_5min                     double precision,         
    outside_par_measurement                          double precision,
    outside_par_measurement_day                      double precision,
    outside_par_measurementnight                     double precision,
    outside_heat_emission_pyrgeometer_5min           double precision,
    outside_heat_emission_pyrgeometer                double precision,
    outside_heat_emission_pyrgeometer_day            double precision,
    outside_heat_emission_pyrgeometernight           double precision,
    outside_netto_radiation_calc_5min                double precision,
    outside_netto_radiation_calc                     double precision,
    fc_temperature_5min                              double precision,             
    fc_temperature                                   double precision,
    fc_rh_5min                                       double precision,
    fc_rh                                            double precision,
    fc_radiation_5min                                double precision,
    fc_radiation                                     double precision,
    fc_radiation_sum_5min                            double precision,
    fc_radiation_sum                                 double precision,
    fc_wind_speed_5min                               double precision,
    fc_wind_speed                                    double precision,
    fc_degree_of_cloudiness18_5min                   double precision,
    fc_degree_of_cloudiness18                        double precision
);

alter table measure
    owner to postgres;

"""

create_simulation_table_query = """
-- auto-generated definition
create table simulation
(
    time              timestamp not null
        constraint simulation_pkey
            primary key,
    par_sensor_above                                 double precision,
    tpipe                                            double precision,
    conpipes_tsuppipe                                double precision,
    pconpipe                                         double precision,
    lmp_elecuse                                      double precision,
    fruit_fresh_weight                               double precision,
    dvs_fruit                                        double precision,
    dry_matter_fract                                 double precision,
    crop_abs                                         double precision,
    elec_price_peakhour                              double precision,
    red_fruits_weight                                double precision,
    mc_pure_air                                      double precision,
    fixed_costs                                      double precision,
    fixed_costs_accumulation                         double precision,       
    fixed_greenhouse_costs                           double precision,
    fixed_co2_costs                                  double precision,    
    fixed_lamp_costs                                 double precision,
    fixed_screen_costs                               double precision,
    fixed_spacing_system_costs                       double precision,
    variable_costs_day_sum                           double precision,         
    variable_costs_accumulation                      double precision,                
    variable_electricity_costs                       double precision,               
    variable_electricity_costs_day_sum               double precision,                       
    variable_heating_costs                           double precision,           
    variable_heating_costs_day_sum                   double precision,                   
    variable_co2_costs                               double precision,       
    variable_co2_costs_day_sum                       double precision,
    gains                                            double precision,
    total_cost                                       double precision,                                     
    net_profit                                       double precision, 
    net_profit_per_year                              double precision,                                   
    sp_plantdensity                                  double precision,
    sp_day_of_harvest_day_number                     double precision,
    sp_heating_temp_setpoint_5min                    double precision,
    sp_vent_ilation_temp_setpoint_5min               double precision,
    sp_leeside_minvent_position_setpoint_5min        double precision,
    sp_net_pipe_minimum_setpoint_5min                double precision,
    sp_Value_to_iSii_1_5min                          double precision,
    sp_energy_screen_setpoint_5min                   double precision,
    sp_blackout_screen_setpoint_5min                 double precision,
    sp_CO2_setpoint_ppm_5min                         double precision,
    sp_humidity_deficit_setpoint_5min                double precision,
    sp_irrigation_interval_time_setpoint_min_5min    double precision,
    temperature_greenhouse_5min                      double precision,
    temperature_greenhouse                           double precision,
    temperature_greenhouse_day                       double precision,
    temperature_greenhousenight                      double precision,
    RH_greenhouse_5min                               double precision,
    RH_greenhouse                                    double precision,
    RH_greenhouse_day                                double precision,
    RH_greenhousenight                               double precision,
    CO2_greenhouse_ppm_5min                          double precision,
    CO2_greenhouse_ppm                               double precision,
    CO2_greenhouse_ppm_day                           double precision,
    CO2_greenhouse_ppm_night                         double precision,
    humidity_deficit_greenhouse_5min                 double precision,
    humidity_deficit_greenhouse                      double precision,
    humidity_deficit_greenhouse_day                  double precision,
    humidity_deficit_greenhouse_night                double precision,
    vent_lee_5min                                    double precision,
    vent_lee                                         double precision,
    vent_lee_day                                     double precision,
    vent_leenight                                    double precision,
    vent_wind_5min                                   double precision,
    vent_wind                                        double precision,
    vent_wind_day                                    double precision,
    vent_wind_night                                  double precision,
    lower_circuit_5min                               double precision,
    lower_circuit                                    double precision,
    lower_circuit_day                                double precision,
    lower_circuitnight                               double precision,
    energy_curtain_5min                              double precision,
    energy_curtain                                   double precision,
    energy_curtain_day                               double precision,
    energy_curtainnight                              double precision,
    blackout_curtain_5min                            double precision,
    blackout_curtain                                 double precision,
    blackout_curtain_day                             double precision,
    blackout_curtainnight                            double precision,
    CO2_actuation_regulation_5min                    double precision,
    CO2_actuation_regulation                         double precision,
    CO2_actuation_regulation_day                     double precision,
    CO2_actuation_regulationnight                    double precision,
    CO2_dosagesum_24h_5min                           double precision,
    CO2_dosagesum_24h                                double precision,
    CO2_dosagesum_24h_day                            double precision,
    CO2_dosagesum_24hnight                           double precision,
    water_supply_minutes_5min                        double precision,
    water_supply_minutes                             double precision,
    drain_5min                                       double precision,
    drain                                            double precision,
    drain_EC_5min                                    double precision,
    drain_EC                                         double precision,
    drain_EC_day                                     double precision,
    drain_EC_night                                   double precision,
    drain_pH_5min                                    double precision,
    drain_pH                                         double precision,
    drain_pH_day                                     double precision,
    drain_pH_night                                   double precision,
    heating_temp_ViP_5min                            double precision,
    heating_temp_ViP                                 double precision,
    heating_temp_ViP_day                             double precision,
    heating_temp_ViP_night                           double precision,
    heating_temp_setpoint                            double precision,
    heating_temp_setpoint_day                        double precision,
    heating_temp_setpoint_night                      double precision,
    vent_ilation_temp_leeside_ViP_5min               double precision,
    vent_ilation_temp_leeside_ViP                    double precision,
    vent_ilation_temp_leeside_ViP_day                double precision,
    vent_ilation_temp_leeside_ViP_night              double precision,
    vent_ilation_tempwind_side_ViP_5min              double precision,
    vent_ilation_tempwind_side_ViP                   double precision,
    vent_ilation_tempwind_side_ViP_day               double precision,
    vent_ilation_tempwind_side_ViP_night             double precision,
    vent_ilation_temp_setpoint                       double precision,
    vent_ilation_temp_setpoint_day                   double precision,
    vent_ilation_temp_setpoint_night                 double precision,
    leeside_window_position_minimum_ViP_5min         double precision,
    leeside_window_position_minimum_ViP              double precision,
    leeside_window_position_minimum_ViP_day          double precision,
    leeside_window_position_minimum_ViP_night        double precision,
    leeside_minvent_position_setpoint                double precision,
    leeside_minvent_position_setpoint_day            double precision,
    leeside_minvent_position_setpoint_night          double precision,
    net_pipe_minimum_ViP_5min                        double precision,
    net_pipe_minimum_ViP                             double precision,
    net_pipe_minimum_ViP_day                         double precision,
    net_pipe_minimum_ViP_night                       double precision,
    net_pipe_minimum_setpoint                        double precision,
    net_pipe_minimum_setpoint_day                    double precision,
    net_pipe_minimum_setpoint_night                  double precision,
    Value_in_iSii_1_5min                             double precision,
    Value_in_iSii_1                                  double precision,
    Value_to_iSii_1                                  double precision,
    energy_screen_ViP_screen_position_5min           double precision,
    energy_screen_ViP_screen_position                double precision,
    energy_screen_ViP_screen_position_day            double precision,
    energy_screen_ViP_screen_position_night          double precision,
    energy_screen_setpoint                           double precision,
    energy_screen_setpoint_day                       double precision,
    energy_screen_setpoint_night                     double precision,
    blackout_screen_ViP_screen_position_5min         double precision,
    blackout_screen_ViP_screen_position              double precision,
    blackout_screen_ViP_screen_position_day          double precision,
    blackout_screen_ViP_screen_position_night        double precision,
    blackout_screen_setpoint                         double precision,
    blackout_screen_setpoint_day                     double precision,
    blackout_screen_setpoint_night                   double precision,
    CO2_ViP_ppm_5min                                 double precision,
    CO2_ViP_ppm                                      double precision,
    CO2_ViP_ppm_day                                  double precision,
    CO2_ViP_ppm_night                                double precision,
    CO2_setpoint_ppm                                 double precision,
    CO2_setpoint_ppm_day                             double precision,
    CO2_setpoint_ppm_night                           double precision,
    humidity_deficit_ViP_5min                        double precision,
    humidity_deficit_ViP                             double precision,
    humidity_deficit_ViP_day                         double precision,
    humidity_deficit_ViP_night                       double precision,
    humidity_deficit_setpoint                        double precision,
    humidity_deficit_setpoint_day                    double precision,
    humidity_deficit_setpoint_night                  double precision,
    water_supply_interval_time_ViP_min_5min          double precision,
    water_supply_interval_time_ViP_min               double precision,
    irrigation_interval_time_setpoint_min            double precision,
    Writeto_iSii_5min                                double precision,
    Writeto_iSii                                     double precision,
    outside_temperature_5min                         double precision,
    outside_temperature                              double precision,
    outside_temperature_day                          double precision,
    outside_temperature_night                        double precision,
    outside_temperature_long_standing_average        double precision,
    outside_rh_5min                                  double precision,
    outside_rh                                       double precision,
    outside_rh_day                                   double precision,
    outside_rh_night                                 double precision,
    outside_humidity_deficit_5min                    double precision,
    outside_humidity_deficit                         double precision,
    outside_humidity_deficit_day                     double precision,
    outside_humidity_deficit_night                   double precision,
    outside_absolute_humidity_content_air_5min       double precision,
    outside_absolute_humidity_content_air            double precision,
    outside_absolute_humidity_content_air_day        double precision,
    outside_absolute_humidity_content_airnight       double precision,
    outside_radiation_5min                           double precision,        
    outside_radiation                                double precision,             
    outside_radiation_sum_5min                       double precision,    
    outside_radiation_sum                            double precision,         
    outside_radiation_sum_longstanding_average       double precision,   
    outside_wind_speed_5min                          double precision,       
    outside_wind_speed                               double precision,            
    outside_wind_speed_day                           double precision,        
    outside_wind_speednight                          double precision,       
    outside_wind_direction_type                      double precision,  
    outside_wind_direction_registration_5min         double precision,      
    outside_wind_direction_registration              double precision,           
    outside_wind_direction_registration_day          double precision,       
    outside_wind_direction_registrationnight         double precision,      
    outside_wind_direction_5min                      double precision,                  
    outside_wind_direction                           double precision,                       
    outside_wind_direction_day                       double precision,                   
    outside_wind_direction_night                     double precision,                                 
    outside_rain_5min                                double precision,                             
    outside_rain                                     double precision,                                  
    outside_rain_day                                 double precision,                              
    outside_rain_night                               double precision,                            
    outside_par_measurement_5min                     double precision,         
    outside_par_measurement                          double precision,
    outside_par_measurement_day                      double precision,
    outside_par_measurementnight                     double precision,
    outside_heat_emission_pyrgeometer_5min           double precision,
    outside_heat_emission_pyrgeometer                double precision,
    outside_heat_emission_pyrgeometer_day            double precision,
    outside_heat_emission_pyrgeometernight           double precision,
    outside_netto_radiation_calc_5min                double precision,
    outside_netto_radiation_calc                     double precision,
    fc_temperature_5min                              double precision,             
    fc_temperature                                   double precision,
    fc_rh_5min                                       double precision,
    fc_rh                                            double precision,
    fc_radiation_5min                                double precision,
    fc_radiation                                     double precision,
    fc_radiation_sum_5min                            double precision,
    fc_radiation_sum                                 double precision,
    fc_wind_speed_5min                               double precision,
    fc_wind_speed                                    double precision,
    fc_degree_of_cloudiness18_5min                   double precision,
    fc_degree_of_cloudiness18                        double precision
);

alter table measure
    owner to postgres;

"""


simulation_result_insert_query = """
INSERT INTO simulation (
    time, temperature_greenhouse_5min, rh_greenhouse_5min, co2_greenhouse_ppm_5min,
    outside_radiation_5min, outside_temperature_5min, outside_rh_5min, 
    outside_wind_speed_5min, par_sensor_above, tpipe, conpipes_tsuppipe, 
    pconpipe, vent_lee_5min, vent_wind_5min, energy_curtain_5min, blackout_curtain_5min, 
    lmp_elecuse, mc_pure_air, fruit_fresh_weight,
    dvs_fruit, dry_matter_fract, crop_abs, elec_price_peakhour, 
    water_supply_minutes_5min, red_fruits_weight, fixed_costs, fixed_costs_accumulation, 
    fixed_greenhouse_costs, fixed_co2_costs, fixed_lamp_costs, fixed_screen_costs, 
    variable_costs_day_sum, variable_costs_accumulation, variable_electricity_costs, 
    variable_electricity_costs_day_sum, variable_heating_costs, variable_heating_costs_day_sum, 
    variable_co2_costs, variable_co2_costs_day_sum, gains, net_profit, total_cost, net_profit_per_year
) VALUES %s
ON CONFLICT ("time") DO UPDATE SET
    (temperature_greenhouse_5min, rh_greenhouse_5min, co2_greenhouse_ppm_5min, 
     outside_radiation_5min, outside_temperature_5min, outside_rh_5min, 
     outside_wind_speed_5min, par_sensor_above, tpipe, conpipes_tsuppipe, 
     pconpipe, vent_lee_5min, vent_wind_5min, energy_curtain_5min, blackout_curtain_5min, 
     lmp_elecuse, mc_pure_air, fruit_fresh_weight, 
     dvs_fruit, dry_matter_fract, crop_abs, elec_price_peakhour, 
     water_supply_minutes_5min, red_fruits_weight, fixed_costs, fixed_costs_accumulation, 
     fixed_greenhouse_costs, fixed_co2_costs, fixed_lamp_costs, fixed_screen_costs, 
     variable_costs_day_sum, variable_costs_accumulation, variable_electricity_costs, 
     variable_electricity_costs_day_sum, variable_heating_costs, variable_heating_costs_day_sum, 
     variable_co2_costs, variable_co2_costs_day_sum, gains, net_profit, total_cost, net_profit_per_year) 
    = 
    (EXCLUDED.temperature_greenhouse_5min, EXCLUDED.rh_greenhouse_5min, EXCLUDED.co2_greenhouse_ppm_5min, 
     EXCLUDED.outside_radiation_5min, EXCLUDED.outside_temperature_5min, EXCLUDED.outside_rh_5min, 
     EXCLUDED.outside_wind_speed_5min, EXCLUDED.par_sensor_above, EXCLUDED.tpipe, EXCLUDED.conpipes_tsuppipe, 
     EXCLUDED.pconpipe, EXCLUDED.vent_lee_5min, EXCLUDED.vent_wind_5min, 
     EXCLUDED.energy_curtain_5min, EXCLUDED.blackout_curtain_5min, 
     EXCLUDED.lmp_elecuse, EXCLUDED.mc_pure_air, EXCLUDED.fruit_fresh_weight, 
     EXCLUDED.dvs_fruit, EXCLUDED.dry_matter_fract, EXCLUDED.crop_abs, EXCLUDED.elec_price_peakhour, 
     EXCLUDED.water_supply_minutes_5min, EXCLUDED.red_fruits_weight, EXCLUDED.fixed_costs, EXCLUDED.fixed_costs_accumulation, 
     EXCLUDED.fixed_greenhouse_costs, EXCLUDED.fixed_co2_costs, EXCLUDED.fixed_lamp_costs, EXCLUDED.fixed_screen_costs, 
     EXCLUDED.variable_costs_day_sum, EXCLUDED.variable_costs_accumulation, EXCLUDED.variable_electricity_costs, 
     EXCLUDED.variable_electricity_costs_day_sum, EXCLUDED.variable_heating_costs, EXCLUDED.variable_heating_costs_day_sum, 
     EXCLUDED.variable_co2_costs, EXCLUDED.variable_co2_costs_day_sum, EXCLUDED.gains, EXCLUDED.net_profit, EXCLUDED.total_cost, EXCLUDED.net_profit_per_year)
"""

simulation_result_columns_to_insert = [
    "time", "temperature_greenhouse_5min", "rh_greenhouse_5min", "co2_greenhouse_ppm_5min",
    "outside_radiation_5min", "outside_temperature_5min", "outside_rh_5min", 
    "outside_wind_speed_5min", "par_sensor_above", "tpipe", "conpipes_tsuppipe", 
    "pconpipe", "vent_lee_5min", "vent_wind_5min",  
    "energy_curtain_5min", "blackout_curtain_5min", 
    "lmp_elecuse", "mc_pure_air", "fruit_fresh_weight", 
    "dvs_fruit", "dry_matter_fract", "crop_abs", "elec_price_peakhour", 
    "water_supply_minutes_5min", "red_fruits_weight", "fixed_costs", "fixed_costs_accumulation", 
    "fixed_greenhouse_costs", "fixed_co2_costs", "fixed_lamp_costs", "fixed_screen_costs", 
    "variable_costs_day_sum", "variable_costs_accumulation", "variable_electricity_costs", 
    "variable_electricity_costs_day_sum", "variable_heating_costs", "variable_heating_costs_day_sum", 
    "variable_co2_costs", "variable_co2_costs_day_sum", "gains", "net_profit", "total_cost", "net_profit_per_year"
]


# simulation_result_insert_query = """
# INSERT INTO simulation (
#     time, temperature_greenhouse_5min, rh_greenhouse_5min, co2_greenhouse_ppm_5min,
#     outside_radiation_5min, outside_temperature_5min, outside_rh_5min, 
#     outside_wind_speed_5min, par_sensor_above, tpipe, conpipes_tsuppipe, 
#     pconpipe, vent_lee_5min, vent_wind_5min, sp_heating_temp_setpoint_5min, 
#     sp_vent_ilation_temp_setpoint_5min, energy_curtain_5min, blackout_curtain_5min, 
#     lmp_elecuse, mc_pure_air, sp_co2_setpoint_ppm_5min, fruit_fresh_weight, 
#     dvs_fruit, dry_matter_fract, crop_abs, sp_plantdensity, elec_price_peakhour, 
#     water_supply_minutes_5min, red_fruits_weight, fixed_costs, fixed_costs_accumulation, 
#     fixed_greenhouse_costs, fixed_co2_costs, fixed_lamp_costs, fixed_screen_costs, 
#     variable_costs_day_sum, variable_costs_accumulation, variable_electricity_costs, 
#     variable_electricity_costs_day_sum, variable_heating_costs, variable_heating_costs_day_sum, 
#     variable_co2_costs, variable_co2_costs_day_sum, gains, net_profit, total_cost, net_profit_per_year
# ) VALUES %s
# ON CONFLICT ("time") DO UPDATE SET
#     (temperature_greenhouse_5min, rh_greenhouse_5min, co2_greenhouse_ppm_5min, 
#      outside_radiation_5min, outside_temperature_5min, outside_rh_5min, 
#      outside_wind_speed_5min, par_sensor_above, tpipe, conpipes_tsuppipe, 
#      pconpipe, vent_lee_5min, vent_wind_5min, sp_heating_temp_setpoint_5min, 
#      sp_vent_ilation_temp_setpoint_5min, energy_curtain_5min, blackout_curtain_5min, 
#      lmp_elecuse, mc_pure_air, sp_co2_setpoint_ppm_5min, fruit_fresh_weight, 
#      dvs_fruit, dry_matter_fract, crop_abs, sp_plantdensity, elec_price_peakhour, 
#      water_supply_minutes_5min, red_fruits_weight, fixed_costs, fixed_costs_accumulation, 
#      fixed_greenhouse_costs, fixed_co2_costs, fixed_lamp_costs, fixed_screen_costs, 
#      variable_costs_day_sum, variable_costs_accumulation, variable_electricity_costs, 
#      variable_electricity_costs_day_sum, variable_heating_costs, variable_heating_costs_day_sum, 
#      variable_co2_costs, variable_co2_costs_day_sum, gains, net_profit, total_cost, net_profit_per_year) 
#     = 
#     (EXCLUDED.temperature_greenhouse_5min, EXCLUDED.rh_greenhouse_5min, EXCLUDED.co2_greenhouse_ppm_5min, 
#      EXCLUDED.outside_radiation_5min, EXCLUDED.outside_temperature_5min, EXCLUDED.outside_rh_5min, 
#      EXCLUDED.outside_wind_speed_5min, EXCLUDED.par_sensor_above, EXCLUDED.tpipe, EXCLUDED.conpipes_tsuppipe, 
#      EXCLUDED.pconpipe, EXCLUDED.vent_lee_5min, EXCLUDED.vent_wind_5min, EXCLUDED.sp_heating_temp_setpoint_5min, 
#      EXCLUDED.sp_vent_ilation_temp_setpoint_5min, EXCLUDED.energy_curtain_5min, EXCLUDED.blackout_curtain_5min, 
#      EXCLUDED.lmp_elecuse, EXCLUDED.mc_pure_air, EXCLUDED.sp_co2_setpoint_ppm_5min, EXCLUDED.fruit_fresh_weight, 
#      EXCLUDED.dvs_fruit, EXCLUDED.dry_matter_fract, EXCLUDED.crop_abs, EXCLUDED.sp_plantdensity, EXCLUDED.elec_price_peakhour, 
#      EXCLUDED.water_supply_minutes_5min, EXCLUDED.red_fruits_weight, EXCLUDED.fixed_costs, EXCLUDED.fixed_costs_accumulation, 
#      EXCLUDED.fixed_greenhouse_costs, EXCLUDED.fixed_co2_costs, EXCLUDED.fixed_lamp_costs, EXCLUDED.fixed_screen_costs, 
#      EXCLUDED.variable_costs_day_sum, EXCLUDED.variable_costs_accumulation, EXCLUDED.variable_electricity_costs, 
#      EXCLUDED.variable_electricity_costs_day_sum, EXCLUDED.variable_heating_costs, EXCLUDED.variable_heating_costs_day_sum, 
#      EXCLUDED.variable_co2_costs, EXCLUDED.variable_co2_costs_day_sum, EXCLUDED.gains, EXCLUDED.net_profit, EXCLUDED.total_cost, EXCLUDED.net_profit_per_year)
# """

# simulation_result_columns_to_insert = [
#     "time", "temperature_greenhouse_5min", "rh_greenhouse_5min", "co2_greenhouse_ppm_5min",
#     "outside_radiation_5min", "outside_temperature_5min", "outside_rh_5min", 
#     "outside_wind_speed_5min", "par_sensor_above", "tpipe", "conpipes_tsuppipe", 
#     "pconpipe", "vent_lee_5min", "vent_wind_5min", "sp_heating_temp_setpoint_5min", 
#     "sp_vent_ilation_temp_setpoint_5min", "energy_curtain_5min", "blackout_curtain_5min", 
#     "lmp_elecuse", "mc_pure_air", "sp_co2_setpoint_ppm_5min", "fruit_fresh_weight", 
#     "dvs_fruit", "dry_matter_fract", "crop_abs", "sp_plantdensity", "elec_price_peakhour", 
#     "water_supply_minutes_5min", "red_fruits_weight", "fixed_costs", "fixed_costs_accumulation", 
#     "fixed_greenhouse_costs", "fixed_co2_costs", "fixed_lamp_costs", "fixed_screen_costs", 
#     "variable_costs_day_sum", "variable_costs_accumulation", "variable_electricity_costs", 
#     "variable_electricity_costs_day_sum", "variable_heating_costs", "variable_heating_costs_day_sum", 
#     "variable_co2_costs", "variable_co2_costs_day_sum", "gains", "net_profit", "total_cost", "net_profit_per_year"
# ]

simulation_forcast_insert_query = """
INSERT INTO simulation (
    time, fc_radiation_5min, fc_temperature_5min, fc_rh_5min, fc_wind_speed_5min
) VALUES %s
"""