version: '3.7'

services:
  ai_greenhouse_climate_controller:
    image: agrifusion:1.0
    container_name : agrifusion
    volumes:
      -  /fileshare/data:/mnt/data
    restart: always

  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - /mnt/data/AGC_data/timescale_data:/var/lib/postgresql/data
    restart: always
    command: -c ssl=off  # SSL을 비활성화

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=croft1!
      - GF_SECURITY_ADMIN_USER=croft
    depends_on:
      - timescaledb
    restart: always
    volumes:
      - /mnt/data/AGC_data/grafana_data:/var/lib/grafana
      - /mnt/data/AGC_data/grafana_provisioning:/etc/grafana/provisioning

  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=callin2@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234!@
    ports:
      - 50003:80