# Greenhouse configuration
LED_iglob_threshold: 500
par_setpoint: 205
LED_max: 75

watt_umol_ratio : 2.1
greenhouse_transmittance : 0.49
energy_screen : 0.7

base_target_DLI : 16
base_LED_umol : 100


# 2021~2023
transplant_date : 2024-08-05 00:00:00
start_date : 2024-08-05 00:00:00
end_date : 2024-12-31 00:00:00


plant_density : "1 56; 32 42; 42 30; 52 20"
